echoserver/EchoServer-0.1.0.jar:
  object_id: eyJvaWQiOiI0ZTRlNzhiY2E2MWUxMjEyMDRlNGU4NmVlYmU1OTEwNGZlN2Qw%0AMmQ3MWI2ZCIsInNpZyI6IlFpRk1Hc3NzUHRYc3hGZW9VQ1BtZGtXZy9sND0i%0AfQ==%0A
  sha: 0de6428519388b19b6ed2316fa77849f306c5bb7
  size: 4164
