---
sqlite/sqlite-autoconf-3070500.tar.gz:
  object_id: eyJvaWQiOiI0ZTRlNzhiY2ExMWUxMjEwMDRlNGU3ZDUxMWY4MjEwNGYzMDY4%0ANjYxY2NmYSIsInNpZyI6ImRUWDZ0ejVOd0lRNlhvWWE2S0V3RFRUdHhvST0i%0AfQ==%0A
  sha: 4e1338497b8da50b84307191bb3418e9ec5715d7
  size: 1551070
ruby/rubygems-1.8.24.tgz:
  object_id: eyJzaWciOiJkZkdFQ2k0aXFua1pESmZvalNKa09tSGtySkU9Iiwib2lkIjoi%0ANGU0ZTc4YmNhNDFlMTIyMjA0ZTRlOTg2M2QwNzYzMDRmYTFjYzI4Nzk3YTki%0AfQ==%0A
  sha: 30f27047e74f7943117736a0d3e224994fee0905
  size: 380101
ruby/rubygems-1.7.2.tgz:
  object_id: eyJvaWQiOiI0ZTRlNzhiY2ExMWUxMjIwMDRlNGU4ZWM2NDg0MzEwNGYzMDY5%0AMDc2OWNkMiIsInNpZyI6IklQQk1BNmxodmNGTHNiTDRkcFR5eDRyWXljRT0i%0AfQ==%0A
  sha: d878ae52f40eb71e59708afc57303172f0327fad
  size: 245606
ruby/ruby-1.9.2-p180.tar.gz:
  object_id: eyJvaWQiOiI0ZTRlNzhiY2EyMWUxMjEwMDRlNGU3ZDUxMWY1NTMwNGYzMDY5%0AMGM4OGZkOSIsInNpZyI6IkE1VlllWVduMVpadFNHbGRpeGM1STgzTU9Jaz0i%0AfQ==%0A
  sha: 6a482bc07239b37bcadf68dda63c65d20dc19ebe
  size: 11158935
ruby/rake-0.8.7.gem:
  object_id: eyJvaWQiOiI0ZTRlNzhiY2E1MWUxMjEwMDRlNGU3ZDUxOTA2Y2QwNGYzMDY5%0AMWM0NWFlMCIsInNpZyI6Img0aWh0QVo0cGNrWWxsYXRpZUhTU251TzArUT0i%0AfQ==%0A
  sha: 91daad079d404b68a7dd179716b9fdd0c195144c
  size: 104960
ruby/ruby-1.8.7-p357.tar.bz2:
  object_id: eyJvaWQiOiI0ZTRlNzhiY2ExMWUxMjEyMDRlNGU4NmVlMTUyOTQwNGYzMDcx%0ANDUzZGFmZiIsInNpZyI6IkFhZCt6VlRiMDd1dVBMa24vZFh2SnVHVUtldz0i%0AfQ==%0A
  sha: ba5ec0ab663976f00fb405be6cfef546bcf0e4e9
  size: 4208157
ruby/bundler-1.2.1.gem:
  object_id: eyJvaWQiOiI0ZTRlNzhiY2EzMWUxMjEyMDRlNGU4NmVlMzk2OTIwNTBhMTYy%0ANTJmMDUyZiIsInNpZyI6InZYOFl0dktMN3k5NWNHWTZnbnpVcFpHY2tUMD0i%0AfQ==%0A
  sha: 0cbe6ad7a41f064d6c11c1058465fffb1bd58069
  size: 226816
java/jre-1.6.0_24-x86_64.tar.gz:
  object_id: eyJvaWQiOiI0ZTRlNzhiY2ExMWUxMjEwMDRlNGU3ZDUxMWY4MjEwNGYzMDY4%0AYzIyN2IzMiIsInNpZyI6IjBjbnFneDZGYnpPN0VHZ0hXZE9odjI1d08zMD0i%0AfQ==%0A
  sha: 0511d833dfd9825a26c18e9d685de64ac0151e85
  size: 34453414
java/jre-1.6.0_24.tar.gz:
  object_id: eyJvaWQiOiI0ZTRlNzhiY2E1MWUxMjIwMDRlNGU4ZWM2ODQwNzcwNGYzMDY4%0AZDQzMzRhNyIsInNpZyI6InRGclltRjJGUURNNDhRS2VaaGZKSkx4Nkt2ST0i%0AfQ==%0A
  sha: 20c6f2cd888b0b01eafdd8f1d6285569ecdca904
  size: 36132629
echoserver/EchoServer-0.1.0.jar:
  object_id: eyJvaWQiOiI0ZTRlNzhiY2E2MWUxMjEyMDRlNGU4NmVlYmU1OTEwNGZlN2Qw%0AMmQ3MWI2ZCIsInNpZyI6IlFpRk1Hc3NzUHRYc3hGZW9VQ1BtZGtXZy9sND0i%0AfQ==%0A
  sha: 0de6428519388b19b6ed2316fa77849f306c5bb7
  size: 4164
